{% set name = "tzfpy" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ringsaturn/tzfpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 43fb97de6fc2abf5021018a308095e296825b772e2c8c2fe6c49176b8a4de669

build:
  number: 1
  skip: true  # [py<37]
  skip: true  # [win and python_impl=="pypy"]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.2.1,<2                      # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.2.1,<2
    - pip
  run:
    - python

test:
  imports:
    - tzfpy
  requires:
    - pip
  commands:
    - pip check
    - python -c "from tzfpy import get_tz; get_tz(116.3883, 39.9289)"

about:
  home: https://github.com/ringsaturn/tzfpy
  summary: 'Convert longitude/latitude to timezone name'
  description: |
    Probably the fastest Python package to convert longitude/latitude to timezone name
  license: MIT
  license_family: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  dev_url: https://github.com/ringsaturn/tzfpy

extra:
  recipe-maintainers:
    - synapticarbors
    - ringsaturn
