context:
  version: "0.16.2"

package:
  name: tzfpy
  version: ${{ version }}

source:
  url: https://github.com/ringsaturn/tzfpy/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 95b6db6eeaa359df4eaab3214954f0f5d146f5f7626dfbcb720b0bdc6cbdd7dd

build:
  number: 0
  skip: win and python_impl == "pypy"
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - python -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.2.1,<2
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.2.1,<2
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - tzfpy
      pip_check: true
  - script:
      - "python -c \"from tzfpy import get_tz; get_tz(116.3883, 39.9289)\""

about:
  summary: Convert longitude/latitude to timezone name
  description: |
    Probably the fastest Python package to convert longitude/latitude to timezone name
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/ringsaturn/tzfpy
  repository: https://github.com/ringsaturn/tzfpy

extra:
  recipe-maintainers:
    - synapticarbors
    - ringsaturn
